### ISSUE TITLE
下载群内压缩包后依然无法打开

### ISSUE THREAD

**Issue by ZJY0516** [nightmare-space/vscode_for_android#10]
下载群内压缩包后（群友提醒应改名为4.6.0）依然无法打开
设备为三星tab s7 安卓12
报错如下
![E712E378D29B62F575A39D03FAA204B8](https://user-images.githubusercontent.com/86695626/206070065-2f102b11-baee-4351-9621-037e9b39ac41.jpg)
![CDAA4B270C0827C5CBFBE0100883DC2A](https://user-images.githubusercontent.com/86695626/206070083-34778ec0-3b63-49da-8ad5-903d7d3e7a36.jpg)
![23A3281E75600DED6B6A5B64BD5B4790](https://user-images.githubusercontent.com/86695626/206070094-231bf848-c1d7-4644-a0da-97ec1f5e912a.jpg)

**Comment by mengyanshou** [comment]
现在还有这个问题吗，有的话直接在群里@我

ZJY0516 ***@***.***> 于2022年12月7日周三 10:08写道：
