### ISSUE TITLE
卡status怎么办

### ISSUE THREAD

**Issue by XiaoTieLa** [nightmare-space/vscode_for_android#11]
卡在status，点了打开vs code窗口打不开网页

**Comment by mengyanshou** [comment]
附上截图最好，然后系统版本，软件版本

**Comment by liaojunhong** [comment]
me too

**Comment by liaojunhong** [comment]
我的是荣耀v6平板 kjr-w09
软件版本是1.2.0

**Comment by mengyanshou** [comment]
收到，我排查一下

**Comment by mengyanshou** [comment]
检查一下是不是没有放对应的外置包版本到/sdcard

**Comment by 1405040117** [comment]
> 检查一下是不是没有放对应的外置包版本到/sdcard @XiaoTieLa @liaojunhong

你好，请问这个外置包版本是什么

**Comment by liaojunhong** [comment]
> 检查一下是不是没有放对应的外置包版本到/sdcard @XiaoTieLa @liaojunhong

是这个吗
![Screenshot_20230616_221732](https://github.com/nightmare-space/vscode_for_android/assets/43564481/19139f05-1019-498d-9a60-c8aeed5e3cd9)

**Comment by mengyanshou** [comment]
/sdcard ，不是/sdcard/Android/data/....这二者区别还是很大，详见https://nightmare.press/pages/e3fb71/

**Comment by abcdesteve** [comment]
> /sdcard ，不是/sdcard/Android/data/....这二者区别还是很大，详见https://nightmare.press/pages/e3fb71/

是将code server解压到这里吗？

**Comment by mengyanshou** [comment]
> > /sdcard ，不是/sdcard/Android/data/....这二者区别还是很大，详见https://nightmare.press/pages/e3fb71/
> 
> 是将code server解压到这里吗？

有没有可能 https://nightmare.press/pages/e3fb71/ 说得很清楚
