### ISSUE TITLE
插件市场里的插件不完整

### ISSUE THREAD

**Issue by 1405040117** [nightmare-space/vscode_for_android#12]
我这边想做C/C++开发，想安装官方的插件：
    https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
但是在跑起来的vscode插件库里搜索不到这个插件。
然后我做了两个尝试，都遇到了问题：
1、我手动下载了插件包到本地，但是不知道怎么传到code-server所在的系统环境内
2、然后我尝试在终端用命令行的方式安装，首先是粘贴文本报错：
    “无法从浏览器的剪贴板中读取。请确保你已授予此网站从剪贴板中读取的访问权限。”
然后我用code-server --install-extension的方式安装也不行，报找不到ID对应的插件。

请问这个问题有没有办法解决，感谢🙏

**Comment by mengyanshou** [comment]
最后找到解决方法了吗，VS Code FA是可以直接浏览/sdcard这个路径的
