### ISSUE TITLE
打开后白屏怎么解决

### ISSUE THREAD

**Issue by XoHADoX** [nightmare-space/vscode_for_android#13]
![Uploading Screenshot_2023-08-12-2
![Screenshot_2023-08-12-22-47-27](https://github.com/nightmare-space/vscode_for_android/assets/140694009/de4c9b77-1849-4754-8921-9f775468fa1b)
2-47-33.png…]()
手机是天翼1号2021
软件版本是1.2.0，系统版本是安卓10

**Comment by XoHADoX** [comment]
![Screenshot_2023-08-12-22-47-33](https://github.com/nightmare-space/vscode_for_android/assets/140694009/b88911be-7887-45f0-9b6a-b3be30a0703a)
![Screenshot_2023-08-12-22-47-27](https://github.com/nightmare-space/vscode_for_android/assets/140694009/f78ac58a-23ae-4311-8f88-af7b0703b02a)

**Comment by mengyanshou** [comment]
天翼1号2021是真没听过了，这种白屏基本就是因为系统WebView版本太低，尝试用Chrome打开`http://127.0.0.1:10000`试试

**Comment by XoHADoX** [comment]
还是白屏

**Comment by mengyanshou** [comment]
那就很抱歉了，不支持这个设备

**Comment by XoHADoX** [comment]
好吧，谢谢大佬
