### ISSUE TITLE
无法打开code FA

### ISSUE THREAD

**Issue by GitZhaoo** [nightmare-space/vscode_for_android#15]
![image](https://github.com/nightmare-space/vscode_for_android/assets/92022206/ae155143-c2a7-440f-9534-46bf1077aeef)
![image](https://github.com/nightmare-space/vscode_for_android/assets/92022206/bd659f8f-6de6-452a-b7b3-9e33b4ce5ee7)
求教下作者该如何解决这个问题

**Comment by mengyanshou** [comment]
根据readme操作

**Comment by GitZhaoo** [comment]
> 根据readme操作

请问/sdcard是要求插入sd卡吗，我在我的平板上面系统目录下创建/sdcard，详情路径写的是"我的平板/sdcard"

**Comment by mengyanshou** [comment]
> > 根据readme操作
> 
> 请问/sdcard是要求插入sd卡吗，我在我的平板上面系统目录下创建/sdcard，详情路径写的是"我的平板/sdcard"

指的就是外置储存根目录，不是内存卡

**Comment by logan00000000** [comment]
> > > 根据readme操作
> > 
> > 
> > 请问/sdcard是要求插入sd卡吗，我在我的平板上面系统目录下创建/sdcard，详情路径写的是"我的平板/sdcard"
> 
> 指的就是外置储存根目录，不是内存卡

可以出一份教程吗，我找不到这个外部存储根目录

**Comment by logan00000000** [comment]
> > > > 根据readme操作
> > > 
> > > 
> > > 请问/sdcard是要求插入sd卡吗，我在我的平板上面系统目录下创建/sdcard，详情路径写的是"我的平板/sdcard"
> > 
> > 
> > 指的就是外置储存根目录，不是内存卡
> 
> 可以出一份教程吗，我找不到这个外部存储根目录

找到对应的教程了，不麻烦您了
https://nightmare.press/pages/e3fb71/#code-fa%E6%98%AF%E5%95%A5
