### ISSUE TITLE
似乎不支持最新版vscode-server【4.16.1】

### ISSUE THREAD

**Issue by huayuprophet** [nightmare-space/vscode_for_android#16]
卡在正在启动vscode按钮页面
重启app就只能看命令行了，webview响应为空

另：
【功能建议】
手动下载、配置version文件有点难搞呀
从app实现客户端从github镜像服务器下载code-server，同时保留旧的手动安装。这样更方便些

**Comment by mengyanshou** [comment]
都开始用vs code了，配置几个文件而已
另外从github下载成功率并不能保证，更多时候，是完全没办法下载

**Comment by Douraben** [comment]
vscode-server4.89.0也不支持 没能安装！

**Comment by mengyanshou** [comment]
请勿带有任何情绪反馈，我近期在住院，清醒时间我会尽力处理一些，已关联新的issue
