### ISSUE TITLE
应用使用正常，但是浏览器无法访问

### ISSUE THREAD

**Issue by chaofanx** [nightmare-space/vscode_for_android#20]
直接使用app使用没什么问题，但是用浏览器访问127.0.0.1:10000基本一直超时会偶尔连上但是很慢，延迟很高，请问这个是什么问题

webview从play商店更新了最新版本，用的浏览器也是最新版chrome

设备是mipad6pro官方系统

**Comment by chaofanx** [comment]
用浏览器主要是想用剪切板

**Comment by mengyanshou** [comment]
有没有尝试关闭省电策略限制，允许后台运行，MIUI有一个省电策略，更改为“无限制”即可

**Comment by doming69** [comment]
改变了无限制但是还是显示访问错误

**Comment by mengyanshou** [comment]
这个问题与设备厂商Rom有关，不好解决
