### ISSUE TITLE
如何通过SSH连接Code FA虚拟的Ubantu系统

### ISSUE THREAD

**Issue by TangAoHan** [nightmare-space/vscode_for_android#24]
可以ping通，没有密码，希望作者提供下虚拟系统的密码，有些东西我需要自定义下

非常感谢

**Comment by mengyanshou** [comment]
可以直接修改密码，在Code FA的Ubuntu中执行passwd即可

TangAoHan ***@***.***> 于2023年10月16日周一 15:34写道：
