### ISSUE TITLE
 无法将code fa里的文件提交到GitHub里面，有没有什么解决办法

### ISSUE THREAD

**Issue by suiducrossing** [nightmare-space/vscode_for_android#28]
如题

**Comment by suiducrossing** [comment]
我想知道到底是我配置的问题还是code fa的问题，还有就是如果不行的话，我想知道大佬是怎么把里面的文件弄出来的

**Comment by mengyanshou** [comment]
外部储存映射到/sdcard了
你想知道是你配置的问题还是Code FA的问题，是不是应该提供更多的信息？

**Comment by suiducrossing** [comment]
/sdcard提示无法写入文件，
上传代码的话就是一直处于加载的状态，文件传不上去

**Comment by suiducrossing** [comment]
应该是链接的问题
git -u origin main
原本的错误是这样的
fatal: unable to access 'https://github.com/        ': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
照着网上的改了之后
fatal:unable to access 'https:     ':Proxy CONNECT aborted

**Comment by mengyanshou** [comment]
我不能理解，这难道不是你没有梯子的缘故吗，没有梯子老实用gitee
