### ISSUE TITLE
小米键盘无法按左键让光标向左跨单词移动

### ISSUE THREAD

**Issue by spy1130** [nightmare-space/vscode_for_android#29]
本人买的小米6的原装键盘，在键盘上让光标向左运动只能在单个单词上向左运动
![Screenshot_2023-12-14-15-23-04-087_com nightmare code](https://github.com/nightmare-space/vscode_for_android/assets/36197456/88a4d8e3-9019-4094-8dc2-03d3828a1813)
![Screenshot_2023-12-14-15-22-41-568_com nightmare code](https://github.com/nightmare-space/vscode_for_android/assets/36197456/db924550-f14f-4bf0-8791-9a099d779411)
![Screenshot_2023-12-14-15-22-47-203_com nightmare code](https://github.com/nightmare-space/vscode_for_android/assets/36197456/56a0e6fe-5aed-4455-8baa-7bbbf8b405b9)
在以下这些情况不能让光标向左运动。不知能否解决这个问题

**Comment by spy1130** [comment]
最后一张图是在<|<这之中

**Comment by mengyanshou** [comment]
不清楚，无能为力，建议换物理键盘再试试，小米平台的键盘很垃圾

**Comment by spy1130** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by spy1130** [comment]
> 不清楚，无能为力，建议换物理键盘再试试，小米平台的键盘很垃圾

我测试了一下，发现是小米讯飞输入法的问题，小米百度输入法就没这个问题

**Comment by destined-wyy** [comment]
您好，apt install gcc后一直显示找不到，您当时是怎么配置cpp环境的啊
