### ISSUE TITLE
some error happened

### ISSUE THREAD

**Issue by ZongZi2233** [nightmare-space/vscode_for_android#32]
![Screenshot_2024-02-11-12-14-31-657_com nightmare code](https://github.com/nightmare-space/vscode_for_android/assets/68067691/f514efea-18fa-4b9d-986f-deeb61497766)

**Comment by ZongZi2233** [comment]
![Screenshot_2024-02-11-20-48-56-873_com nightmare code](https://github.com/nightmare-space/vscode_for_android/assets/68067691/0694d336-ad3f-4b55-82c1-69d6bc25e97a)

**Comment by mengyanshou** [comment]
please try new version

**Comment by mengyanshou** [comment]
I'll close this issue.
