### ISSUE TITLE
有什么办法能使用node.js么

### ISSUE THREAD

**Issue by octoberdreams** [nightmare-space/vscode_for_android#35]
太需要了

**Comment by mengyanshou** [comment]
没有尝试过apt install nodejs吗

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: octoberdreams ***@***.***>
Sent: Friday, March 8, 2024 7:44:16 PM
To: nightmare-space/vscode_for_android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nightmare-space/vscode_for_android] 有什么办法能使用node.js么 (Issue #35)


太需要了

―

**Comment by octoberdreams** [comment]
![Uploading IMG_20240329_091530.jpg…]()

**Comment by mengyanshou** [comment]
发了个啥，打不开，建议按原始的VS Code遇见问题的是，进行搜索，查询
