### ISSUE TITLE
安装Python插件的时候，提示：Couldn't start client Python Tools

### ISSUE THREAD

**Issue by wangzhatian** [nightmare-space/vscode_for_android#4]
并且运行Python脚本的时候
```
root@localhost:~/.local/share/code-server/User# python /root/.local/share/code-server/User/test.py
bash: python: command not found
root@localhost:~/.local/share/code-server/User# 

```
![image](https://user-images.githubusercontent.com/40046246/172129763-c457a31f-8dfc-4dcd-84bf-c9ffc4d937f1.png)

**Comment by mengyanshou** [comment]
执行apt update同步源，执行apt install python安装python包

**Comment by wangzhatian** [comment]
apt install python 安装的版本是Python 2.7
![image](https://user-images.githubusercontent.com/40046246/172277270-3e85c10a-62c7-4b2e-a1c5-0d2d3d105ff6.png)

**Comment by mengyanshou** [comment]
视屏中有提到这个问题，apt install python3就行了，这是ubuntu的使用问题，跟这个仓库关系不大了
