### ISSUE TITLE
没有终端可以用的快捷键

### ISSUE THREAD

**Issue by pizhd** [nightmare-space/vscode_for_android#44]
既然终端都做出来了,终端的命令按钮快捷键应该也可以做吧。。。

**Comment by mengyanshou** [comment]
第一个终端只是一个引导界面，在整个Code FA中，不属于主要的功能，并且对应的源的deb是飞常少的。
如实在需要，欢迎提交pr

**Comment by pizhd** [comment]
> 第一个终端只是一个引导界面，在整个Code FA中，不属于主要的功能，并且对应的源的deb是飞常少的。 如实在需要，欢迎提交pr

欸？你是活跃的账号吗？我的意思不是引导界面的那个终端。
我是指快捷键，比如termux里的TAB,CTRL这些功能键，在安卓平板（我的是8寸平板）上，因为没有物理键盘，在使用诸如格式化，或者在code-server终端里需要按TAB时，十分不方便。不知道有没有办法在键盘上添加一行功能按键？

**Comment by mengyanshou** [comment]
第一句话我不太理解你的意思，并且你的反馈会让人感觉不舒服
就是Code Server内部的终端缺少一些快捷键对吧，可是整个Code Server是使用的开源code-server发布的zip包，需要定制成本非常高

**Comment by mengyanshou** [comment]
我先关闭这个issue
