### ISSUE TITLE
git无法提交代码

### ISSUE THREAD

**Issue by ajjdxns** [nightmare-space/vscode_for_android#49]
连命令行都没用

**Comment by ajjdxns** [comment]
![Screenshot_20240521_021218](https://github.com/nightmare-space/vscode_for_android/assets/136149181/c7a45226-9302-4bb8-9a0f-522730eacf4c)

**Comment by mengyanshou** [comment]
那请用命令行

**Comment by ajjdxns** [comment]
> 连命令行都没用

没看见吗？

**Comment by ajjdxns** [comment]
> 那请用命令行

前面的连命令行都没有没有看见吗？

**Comment by mengyanshou** [comment]
我不会，另请高人
