### ISSUE TITLE
【需求】能否编译一版微软的vscode_cli版本

### ISSUE THREAD

**Issue by jayking0912** [nightmare-space/vscode_for_android#53]
有些插件微软的vscode_cli支持度会更好，尤其是c#等微软官方的插件，是否可以编译一版vscode_cli版本？
vscode_cli 在ubuntu下运行下面命令来本地运行：
`./code serve-web --host 0.0.0.0 --without-connection-token --accept-server-license-terms --log trace --verbose`

**Comment by mengyanshou** [comment]
这个运行命令有什么区别吗
