### ISSUE TITLE
三星平板无法安装

### ISSUE THREAD

**Issue by wmlhbb484** [nightmare-space/vscode_for_android#55]
三星平板好像只能打开apk后缀的安装包，这个好像用不了

**Comment by mengyanshou** [comment]
这难道不是apk后缀的安装包吗

**Comment by wmlhbb484** [comment]
> 这难道不是apk后缀的安装包吗
![df7642a43e3f3058258f0c586517e6e](https://github.com/user-attachments/assets/310a14a8-3739-4a41-850c-a235dab2c642)
我打开是这样的 找不到安装的窗口

**Comment by mengyanshou** [comment]
你有没有仔细看发布的版本在哪儿？以及官网的使用介绍？
https://github.com/nightmare-space/vscode_for_android/releases

**Comment by wmlhbb484** [comment]
> 你有没有仔细看发布的版本在哪儿？以及官网的使用介绍？ https://github.com/nightmare-space/vscode_for_android/releases

好的好的 我之前没点进去看 谢谢dalao

**Comment by mengyanshou** [comment]
> > 你有没有仔细看发布的版本在哪儿？以及官网的使用介绍？ https://github.com/nightmare-space/vscode_for_android/releases
> 
> 好的好的 我之前没点进去看 谢谢dalao

https://nightmare.press/pages/e3fb71/ 教程
