### ISSUE TITLE
不兼容ARM 64位？

### ISSUE THREAD

**Issue by huangsijun17** [nightmare-space/vscode_for_android#56]
安装完运行时提示需要Linux32

**Comment by mengyanshou** [comment]
不懂，反馈能否详细点？

**Comment by huangsijun17** [comment]
![Screenshot_2024-10-12-09-39-46-24_587dcc03db2399f6bfb46354a895e9dc.png](https://github.com/user-attachments/assets/32a17c82-3d79-423b-834a-e1ccbc73f3b1)

看这报错，应该所有arm64的通病吧。

**Comment by mengyanshou** [comment]
目前在大部分arm64的设备上运行很好哈，反馈需要带上设备更多信息，不然我没办法排查问题
