### ISSUE TITLE
没有git，使用termux安装后，无法修改git.path

### ISSUE THREAD

**Issue by jmf240625394** [nightmare-space/vscode_for_android#66]
华为平板安装后，很nice，只是没有git，使用termux安装git之后，发现vscodefa无法配置git.path，json配置文件无法打开，各位同好有没有好的解决办法？

**Comment by mengyanshou** [comment]
我没太理解使用termux安装git是什么意思

**Comment by jmf240625394** [comment]
安装vscodefa很顺利，我这边用vscode主要用来看自己的markdown文档的，而我的文档又是放在gitee上，因此老是提示没有可用的git，没有办法同步和提交到gitee上；

**Comment by jmf240625394** [comment]
找不到git命令后，我各种google，发现有一个工具是termux(本质是在安卓上安装一个ubuntu)，通过这个工具可以安装git命令，但是vscodefa找不到这个git客户端

**Comment by mengyanshou** [comment]
你没问过gpt ubuntu怎么装git吗

**Comment by mengyanshou** [comment]
你termux装git和code fa有什么关系呢

**Comment by jmf240625394** [comment]
> 你没问过gpt ubuntu怎么装git吗

问了kimi，给出gitbash和termux，gitbash和termux在商城里面没有哇，我选择了很多人都用的方案termux呢，先安装ermux，然后通过ermux安装的git呢；

**Comment by jmf240625394** [comment]
> 你termux装git和code fa有什么关系呢

codefa需要依赖系统的git客户端呢

**Comment by jmf240625394** [comment]
codefa本身是一个强大的独立工具，但是他自身有很多的功能本身就依赖本机的git客户端；像我平时电脑上通常会用VSCode和VSCodium，前者用来写代码，后者用来专门写文档；两者都借助电脑的gitbash这个客户端来pull、push代码和文档，只要在电脑上安装了gitbash，vscode能自动找到git命令；但是安卓平板有点特殊，暂时没有找到适合这个系统的gitbash安装包；

![image](https://github.com/user-attachments/assets/14285505-9ba9-4e33-8401-e6f78142f6be)
借助这张截图是不是要好点，这是我在电脑端与gitee通常交互的点，不知道我有没有表达清楚哈；

当然这个是一个锦上添花的功能，codefa即使不能通过这个图形界面更新代码，也没有关系；不影响我这边的使用，每次代码仓库有更新后，我要进termux，执行git命令更新一下代码就好

**Comment by mengyanshou** [comment]
我是真搞不懂啊，你能不能google或者baidu以下ubuntu装git怎么装，问下gpt，你pc的vs code难道就是天生就有git环境的吗

**Comment by mengyanshou** [comment]
> > 你termux装git和code fa有什么关系呢
> 
> codefa需要依赖系统的git客户端呢

你应该学习的是怎么使用 vs code，那么大一个终端在那里，有什么是不能装的你告诉我

**Comment by mengyanshou** [comment]
你要在code fa用git要跑去termux装，和别人给了你个微信你跑去qq加有什么区别

**Comment by mengyanshou** [comment]
<img width="845" alt="截屏2024-12-27 01 38 07" src="https://github.com/user-attachments/assets/8bae662d-c4a4-48a0-aa7a-ab7651488be4" />
我的建议是，你如果连很多基本的东西都弄不清楚，就不要使用 vs code了

**Comment by mengyanshou** [comment]
你怎么不问问termux安装的git别的地方怎么用？还是需要我帮你问？Github Issue 主要收集 Code FA 本身的问题，而不是你自身完全不懂技术，需要通过开一个Issue来让世人教你

**Comment by jmf240625394** [comment]
莫生气，气坏伤身体，你讲的有道理，我回头在vscode的终端安装一下，感谢
