### ISSUE TITLE
can not stat './home'

### ISSUE THREAD

**Issue by wzkzs** [nightmare-space/vscode_for_android#9]
小米手机安装测试，无法使用
一直卡在这里：
![Screenshot_2022-10-15-22-52-44-457_com.nightmare.code.jpg](https://user-images.githubusercontent.com/57616924/195992978-182b312f-b657-4a62-a533-4fa1b1d8be49.jpg)

**Comment by mengyanshou** [comment]
需要外置包，添加群761959652
